name: Assert No Trailing Whitespace

on:
  push:
    branches:
      - master

jobs:
  check-whitespace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Assert No Trailing Whitespace
      uses: AlexanderKosnac/assert-no-tws@v1.0.0
      with:
        path: '.'
        extensions: ''
