name: Build and Release

permissions: write-all

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Build
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Build
        run: mvn clean package -DskipTests

      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/*.jar
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release for ${{ github.ref_name }}.
          draft: false
          prerelease: false
