name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'oracle'
          java-version: '25'

      - name: Build
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/*.jar
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release for ${{ github.ref_name }}.
          draft: false
          prerelease: false
